### ISSUE TITLE
ford (or doxygen) documentation

### ISSUE THREAD

**Issue by urbanjost** [jacobwilliams/odepack#5]
The documentation/comments need updated to format well with ford or doxygen.

1. ford or doxygen (?)
2. auto-build of documentation from CD/CI (?)
3. should documentation be hosted on github site (?) If so, under main branch or gh-pages?

I will concentrate on polishing up the documentation in the M_main/ directory for now. This will obviously be an on-going task, especially if the API changes.

**Comment by jacobwilliams** [comment]
I'm personally partial to Ford, autobuild with GitHub CI, and then pushed to a gh-pages branch so it would be hosted at https://jacobwilliams.github.io/odepack/

I have all the code to do this (which I basically just copy paste into all my projects) :)

**Comment by urbanjost** [comment]
That is exactly what I was thinking, with some thought towards doxygen for the call graphs; but otherwise I like and having been using ford, although I had problems getting the CI/CD build to build into the gh-pages branch when I tried that. If you can put that into place I will format a couple of the comment sections in M_main and see how it goes.

**Comment by jacobwilliams** [comment]
Yep, I'll set that up!

**Comment by jacobwilliams** [comment]
FYI: I always use this procedure: https://gist.github.com/ramnathv/2227408 to make the `gh-pages` branch. Then look at the CI.yml file I just committed and you can see how I use the `github-pages-deploy-action` action to push the docs.

**Comment by urbanjost** [comment]
Thanks. I will try that. At one time I converted all my github repos to automatically generate their documentation and had  trouble, 

Got hung up on tables which are all through the documentation and ford mangles them. The CSS style completely collapses all the margins and borders and other issues that make them very ugly. Already found related issues on ford web page that are months old so might have to revert back to simple text blocks.

**Comment by urbanjost** [comment]
FYI: ford developers working on issues with tables, so the comments in the src/M_main sources which are really the main user documentation are on hold, but I think all the other code renders reasonably enough to be acceptable, albeit it all needs some rework to look good in ford.  Unfortunately ford does not follow include files for presenting the code, so the documentation seems to be working OK in ford, but cannot browse the source code that is included from the ford view. Feel free to change the README or anything else; I would like to acknowledge the plusFORT tools but it this moves forward not sure my verbiage is of any further use.

the dlsoda documentation looks pretty close to what I want to get the others in src/M_main to look like, after which I think everything is at least presentable and can be a low priority to polish.
Some of them were just coming up as garbage in ford, which did not look nice.
