### ISSUE TITLE
Double precision array element initialized with single precision value

### ISSUE THREAD

**Issue by mecej4g** [jacobwilliams/odepack#9]
In file `lsodes.f90` in the `example` directory, in subroutine `Edit` we have the initialization

> data yex/6.687279d-01 , 9.901910d-01 , 7.603061d-01 ,           &
 & 8.077979d-01 , 1.170226e+00 , 8.810605d-01 , 5.013331d-01 ,  &

Note the "e+00". That should have been "d+00". This error can be seen in the LLNL and Netlib F77 sources of Odepack, as well. I suppose that we are so jaded by all the warnings that we see when compiling refactored F77 code that this minor bug has escaped detection for decades!

**Comment by urbanjost** [comment]
Particularly easy to miss as the values only specify 7 digits as well. I know the sometimes overwhelming messages have hidden several actual issues multiple times for me; making them harder to find. I changed it.
